name: zodgame

on:
  schedule:
  - cron: "0 0 * * *"
  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:
jobs:
  sign-in:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install requirements
      run: |
        pip3 install -r ./zodgame/requirements.txt
    - name: Run 
      run: |
        python3 ./zodgame/zodgame.py "${{secrets.ZODGAME_COOKIE}}"
  keepalive-job:
    name: Keepalive Workflow
    if: ${{ always() }}
    needs: sign-in
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
